README.md
examples/advanced-web-service/__snapshots__/chart.test.ts.snap
examples/advanced-web-service/chart.ts
examples/advanced-web-service/example.env
examples/advanced-web-service/main.ts
lib/data/config-map.ts
lib/data/hash-util.ts
lib/data/index.ts
lib/data/secret.ts
lib/index.ts
package-lock.json
package.json
test/data/__snapshots__/config-map.test.ts.snap
test/data/__snapshots__/secret.test.ts.snap
test/data/config-map.test.ts
test/data/hash-util.test.ts
test/data/secret.test.ts

* https://github.com/talis/platform/issues/5343
* Can load values from `.env` files
* Both can append a hash of its own contents to its name the same way [`kustomize`](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/generatoroptions/) does.
* Update advanced WebService example to include ConfigMap with an `.env` file.

feat: add ConfigMap and Secret constructs

---

examples/advanced-web-service/__snapshots__/chart.test.ts.snap
examples/background-worker/__snapshots__/chart.test.ts.snap
examples/simple-web-service/__snapshots__/main.test.ts.snap
lib/background-worker/background-worker.ts
lib/common/container-props.ts
lib/web-service/web-service.ts
test/background-worker/__snapshots__/background-worker.test.ts.snap
test/background-worker/background-worker.test.ts
test/web-service/__snapshots__/resque-web.test.ts.snap
test/web-service/__snapshots__/web-service.test.ts.snap
test/web-service/web-service.test.ts

- Ensure container name is set even if `app` labels isn't
- Use custom selector `app` label in setting the container name
- Allow to explicitly set container name

fix: ensure container name is set and correct use of service label

---

README.md
examples/simple-web-service/__snapshots__/main.test.ts.snap
lib/common/name-util.ts
lib/web-service/annotation-util.ts
lib/web-service/env-util.ts
package.json
test/common/name-util.test.ts
test/web-service/__snapshots__/resque-web.test.ts.snap
test/web-service/__snapshots__/web-service.test.ts.snap
test/web-service/annotation-util.test.ts
test/web-service/env-util.test.ts

Use the recently created enums in the helper functions.

fix: use deployment and region enums in helper functions

---

README.md
examples/cron-job/README.md
examples/cron-job/__snapshots__/chart.test.ts.snap
examples/cron-job/cdk8s.yaml
examples/cron-job/chart.test.ts
examples/cron-job/chart.ts
examples/cron-job/main.ts
lib/cron-job/cron-job-props.ts
lib/cron-job/cron-job.ts
lib/cron-job/index.ts
lib/index.ts
test/cron-job/__snapshots__/cron-job.test.ts.snap
test/cron-job/cron-job.test.ts

- this relates to talis/platform#5428
This P/R adds a new cdk8s construct that represents a Cron-Job which can be executed based on a defined schedule.

feat: add cron-job construct

---

README.md
examples/job/README.md
examples/job/__snapshots__/chart.test.ts.snap
examples/job/cdk8s.yaml
examples/job/chart.test.ts
examples/job/chart.ts
examples/job/main.ts
lib/index.ts
lib/job/index.ts
lib/job/job-props.ts
lib/job/job.ts
test/job/__snapshots__/job.test.ts.snap
test/job/job.test.ts

- This relates to talis/platform#5461
This P/R adds a new cdk8s construct that represents a single run Job which can be  used to complete tasks such as seeding data in a database.

feat: adds a Job construct

---

README.md
examples/redis/README.md
examples/redis/__snapshots__/chart.test.ts.snap
examples/redis/cdk8s.yaml
examples/redis/chart.test.ts
examples/redis/chart.ts
examples/redis/main.ts
lib/index.ts
lib/redis/index.ts
lib/redis/redis-props.ts
lib/redis/redis.ts
test/redis/__snapshots__/redis.test.ts.snap
test/redis/redis.test.ts

- This relates to talis/platform#5463
This P/R adds a new cdk8s construct that represents a simple single node redis service. This is not intended to be used as a production service (we have elastic cache for that) but rather for on demand instances.

feat: adds redis construct

---

README.md
examples/mongo/README.md
examples/mongo/__snapshots__/chart.test.ts.snap
examples/mongo/cdk8s.yaml
examples/mongo/chart.test.ts
examples/mongo/chart.ts
examples/mongo/main.ts
lib/index.ts
lib/mongo/index.ts
lib/mongo/mongo-props.ts
lib/mongo/mongo.ts
test/mongo/__snapshots__/mongo.test.ts.snap
test/mongo/mongo.test.ts

- This relates to talis/platform#5462
This P/R adds a new cdk8s construct that represents a simple single node Mongo service. This is not intended to be used as a production service but rather for on demand instances.

feat: adds mongo construct

---

examples/cron-job/__snapshots__/chart.test.ts.snap
examples/cron-job/chart.ts
examples/job/__snapshots__/chart.test.ts.snap
examples/job/chart.ts
lib/cron-job/cron-job-props.ts
lib/cron-job/cron-job.ts
lib/job/job-props.ts
lib/job/job.ts
lib/mongo/mongo.ts
lib/redis/redis.ts
test/cron-job/__snapshots__/cron-job.test.ts.snap
test/cron-job/cron-job.test.ts
test/data/config-map.test.ts
test/data/secret.test.ts
test/job/__snapshots__/job.test.ts.snap
test/job/job.test.ts
test/mongo/mongo.test.ts
test/redis/redis.test.ts
test/test-util.ts
test/web-service/web-service.test.ts

* Relates to https://github.com/talis/platform/issues/5482
* When trying to apply Job, it complained that `restartPolicy` is required.
* With `restartPolicy` exposed it also makes sense to expose `backoffLimit` prop.
* Allow to get Mongo's and Redis' service name from the object, so that we can reference it in the ConfigMaps when configuring on-demand chart.

feat: add restartPolicy and backoffLimit

---

examples/mongo/__snapshots__/chart.test.ts.snap
examples/redis/__snapshots__/chart.test.ts.snap
lib/mongo/mongo.ts
lib/redis/redis.ts
test/mongo/__snapshots__/mongo.test.ts.snap
test/redis/__snapshots__/redis.test.ts.snap

* `Mb` are not correct units, while applying I got error:
> v1.ResourceRequirements.Limits: unmarshalerDecoder: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$', error found in#10 byte of ...|y":"500Mb"}}

fix: correct memory units in Mongo and Redis

---

examples/mongo/__snapshots__/chart.test.ts.snap
lib/mongo/mongo.ts
test/mongo/__snapshots__/mongo.test.ts.snap
test/mongo/mongo.test.ts

Kubernetes uses `command` and `args` for defining how a container is started. In Docker, it's `entrypoint` and `command`.
They are each other's equivalent in that order, meaning specifying a `command` in Kubernetes completely overrides the `entrypoint`. When passing only flags, `args` is meant to be used.

fix: use args for Mongo rather than command

---

examples/mongo/__snapshots__/chart.test.ts.snap
examples/redis/__snapshots__/chart.test.ts.snap
lib/mongo/mongo.ts
lib/redis/redis.ts
test/mongo/__snapshots__/mongo.test.ts.snap
test/mongo/mongo.test.ts
test/redis/__snapshots__/redis.test.ts.snap
test/redis/redis.test.ts

- feat: add getDnsName helper for Mongo and Redis
- fix: mount Mongo volume under correct path
- fix: make Mongo and Redis services headless

fix: make Mongo and Redis services headless

---

examples/cron-job/README.md
lib/cron-job/cron-job.ts
package-lock.json
package.json
test/cron-job/cron-job.test.ts

- talis/platform#5474
Adds validation of the passed in schedule for the cron job against 5 or 6 long cron syntax using cron-parser.

feat: cron job schedule validation

---

.prettierignore
jest.config.js
lib/job/job-props.ts
package-lock.json
package.json
test/background-worker/__snapshots__/background-worker.test.ts.snap
test/background-worker/background-worker.test.ts
test/cron-job/__snapshots__/cron-job.test.ts.snap
test/cron-job/cron-job.test.ts
test/jest.d.ts
test/jest.setup.js
test/job/__snapshots__/job.test.ts.snap
test/job/job.test.ts
test/mongo/__snapshots__/mongo.test.ts.snap
test/mongo/mongo.test.ts
test/redis/redis.test.ts
test/web-service/__snapshots__/web-service.test.ts.snap
test/web-service/web-service.test.ts

We had to fix our constructs a few times now because some properties weren't being handled by the constructs, even though they were available in the interface. This PR addresses that:
- In the "All the props" tests we now use `Required<T>` which will ensure that we are actually setting all available props. Use `Omit<T, "prop">` where some properties an exclusive with others, and make sure we have tests to cover them.
- A custom Jest matcher, `toHaveAllProperties`, is a dummy way to check that all keys from the props object are present in the resulting, synthesized object. Because not all construct props are Kubernetes props, we allow to omit some key names - these keys are the prime candidates to have their own, more detailed tests.

test: verify all props are handled

---

examples/mongo/__snapshots__/chart.test.ts.snap
lib/mongo/mongo-props.ts
lib/mongo/mongo.ts
test/mongo/__snapshots__/mongo.test.ts.snap
test/mongo/mongo.test.ts

- talis/platform#5550
Moves mongo to use a persistent storage volume over empty directory, this will allow the mongo pod to be restarted and data not lost i.e. seed data will stay around
Allows the end user to specify the resources for mongo pod incase these need to be higher i.e. when running a load test

feat: mongo persistent storage and resource limits

---

lib/cron-job/cron-job-props.ts
lib/cron-job/cron-job.ts
test/cron-job/__snapshots__/cron-job.test.ts.snap
test/cron-job/cron-job.test.ts

Adds [`startingDeadlineSeconds`](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#starting-deadline) to cron job configuration.

feat: add startingDeadlineSeconds to cron job

---

examples/cron-job/__snapshots__/chart.test.ts.snap
lib/cron-job/cron-job-props.ts
lib/cron-job/cron-job.ts
test/cron-job/__snapshots__/cron-job.test.ts.snap
test/cron-job/cron-job.test.ts

Adds `successfulJobsHistoryLimit` and `failedJobsHistoryLimit` to cron job configuration

feat: add successfulJobsHistoryLimit and failedJobsHistoryLimit to cron job

---

lib/data/secret.ts
test/data/secret.test.ts

- https://github.com/talis/platform/issues/5579
Redact secrets in env var `CDK8S_REDACT_SECRET_DATA` is set.
This is used for snapshot testing where we want to create a snapshot that does not contain a secret.

feat: plat-5579 redact secrets if env var is set

---

lib/web-service/web-service-props.ts
lib/web-service/web-service.ts
test/web-service/__snapshots__/web-service.test.ts.snap
test/web-service/web-service.test.ts

Change `cpuTargetUtilization` on the web service HPA to be optional and add another parameter of `memoryTargetUtilization` to allow scaling a web service by cpu, memory or both. 
The props validator checks at least one of these is specified when configuring a HPA.

feat: add HPA scaling based on memory to web service

---

e2e/full-stack.bats
e2e/full-stack.e2e.ts
e2e/lib/test_helper.bash
e2e/web-service-canary.bats
lib/background-worker/background-worker.ts
lib/common/workload-props.ts
lib/web-service/web-service-props.ts
lib/web-service/web-service.ts
test/background-worker/__snapshots__/background-worker.test.ts.snap
test/background-worker/background-worker.test.ts
test/web-service/__snapshots__/web-service.test.ts.snap
test/web-service/web-service.test.ts

- Allow for WebService's additional external hostnames.
- Allow to set hostAliases in WebService and BackgroundWorker.
- Always retry up to 20 times in e2e tests.
- Fix external DNS being set on the canary Ingress (with the same hostname as non-canary).

feat: allow for WebService additional external hostnames

---

lib/background-worker/background-worker-props.ts
lib/background-worker/background-worker.ts
test/background-worker/__snapshots__/background-worker.test.ts.snap
test/background-worker/background-worker.test.ts

* References https://github.com/talis/platform/issues/5956.
* Add `restartPolicy` prop to `BackgroundWorker`.

feat: add restartPolicy prop to BackgroundWorker

---

.prettierignore
examples/background-worker/__snapshots__/chart.test.ts.snap
lib/web-service/resque-web.ts
package-lock.json
package.json
test/web-service/__snapshots__/resque-web.test.ts.snap
test/web-service/resque-web.test.ts

- The `talis/resque-web` container image now includes a `/status` endpoint, this adds Pod probes and configures ALB's health check to use that.
- Fix how overriding nested props works.

feat: add /status check to ResqueWeb

---

examples/advanced-web-service/__snapshots__/chart.test.ts.snap
examples/background-worker/__snapshots__/chart.test.ts.snap
examples/simple-web-service/__snapshots__/main.test.ts.snap
lib/web-service/web-service.ts
test/web-service/__snapshots__/resque-web.test.ts.snap
test/web-service/__snapshots__/web-service.test.ts.snap

Updates the web service construct to have an ingress rule for the `/server-status` endpoint and adds an ALB rule to return a fixed 404 from the ALB for this.
This should still allow instana internal to the cluster and talking to the pods directly to get the `/server-status` endpoint but prevent any traffic coming via the ingress to access this.

feat: restrict server-status endpoint

---

e2e/full-stack.e2e.ts
examples/advanced-web-service/__snapshots__/chart.test.ts.snap
examples/cron-job/chart.ts
examples/job/chart.ts
imports/k8s.ts
lib/background-worker/background-worker-props.ts
lib/background-worker/background-worker.ts
lib/common/container-props.ts
lib/cron-job/cron-job-props.ts
lib/cron-job/cron-job.ts
lib/job/job-props.ts
lib/job/job.ts
lib/memcached/memcached.ts
lib/mongo/mongo.ts
lib/postgres/postgres.ts
lib/redis/redis.ts
lib/talis-chart/calculate-resource-quota.ts
lib/web-service/web-service-props.ts
lib/web-service/web-service.ts
package-lock.json
package.json
test/background-worker/background-worker.test.ts
test/cron-job/cron-job.test.ts
test/job/job.test.ts
test/talis-chart/talis-chart.test.ts
test/web-service/__snapshots__/web-service.test.ts.snap
test/web-service/web-service.test.ts

* References https://github.com/talis/platform/issues/5989
* Update Kubernetes schema import to 1.23.
* Update settings to use enums - previously import would allow strings, now enums are provided.
* Update HorizontalPodAutoscaler from v2beta2 to v2.

feat: update Kubernetes schema

---

examples/mongo/__snapshots__/chart.test.ts.snap
lib/mongo/mongo-props.ts
lib/mongo/mongo.ts
test/mongo/__snapshots__/mongo.test.ts.snap
test/mongo/mongo.test.ts

https://github.com/talis/platform/issues/5939
Update the mongo construct to have optional parameter to expose the mongo service on an internal nlb allowing all internal traffic.

feat: expose mongo service on internal nlb

---

examples/advanced-web-service/__snapshots__/chart.test.ts.snap
examples/simple-web-service/__snapshots__/main.test.ts.snap
lib/common/value-util.ts
lib/talis-chart/calculate-resource-quota.ts
lib/web-service/resque-web.ts
lib/web-service/web-service-props.ts
lib/web-service/web-service.ts
test/common/__snapshots__/value-util.test.ts.snap
test/common/value-util.test.ts
test/web-service/__snapshots__/web-service.test.ts.snap
test/web-service/resque-web.test.ts
test/web-service/web-service.test.ts

* Related to https://github.com/talis/platform/issues/6711.
* Introduce PodDisruptionBudget into WebService construct, default to `minAvailable: 1`.

feat!: add PodDisruptionBudget to WebService

---

package-lock.json
package.json
release.config.js

* downgrade `conventional-changelog-conventionalcommits` to v6 - v7 just causes semantic-release to die on:
```
Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
```
* simplify release config by putting preset at the top level rather than for each individual plugin.

chore: make semantic-release work

---

lib/common/index.ts
lib/common/metadata-util.ts
test/common/metadata-util.test.ts

Add a utility function that allows to add a set of labels to objects, including to their nested Pod templates.
Example use:
```ts
import { Helm } from "cdk8s";
import { addLabels } from "talis-cdk8s-constructs";
const helm = new Helm(chart, "helm-template", {
repo: "https://aws.github.io/eks-charts",
chart: "aws-load-balancer-controller",
releaseName: "aws-load-balancer-controller",
version: "1.6.1",
});
addLabels(helm.apiObjects, {
"my-label": "my-value",
});
```

feat: add addLabels utility

---

.circleci/config.yml
package.json

Locks down the node version in CircleCI to `18.17.1` this was defaulting to `20.11.0`

chore: lock node version in circleci

---

.circleci/config.yml
.gitignore
.npmignore
e2e/autoscaling-worker.e2e.ts
e2e/full-stack.e2e.ts
e2e/rails-app.e2e.ts
lib/common/container-util.ts
lib/common/index.ts
lib/memcached/memcached.ts
lib/mongo/init/setup-replset.sh
lib/mongo/mongo.ts
lib/postgres/postgres.ts
lib/redis/redis.ts
test/common/container-util.test.ts
test/memcached/memcached.test.ts
test/mongo/__snapshots__/mongo.test.ts.snap
test/mongo/mongo.test.ts
test/postgres/postgres.test.ts
test/redis/redis.test.ts

- **feat:** add `getWaitForPortContainer` to Memcached, Mongo, Postgres, and Redis
- add `makeWaitForPortContainer` utility function
- add `port` property to expose the port
- **feat:** add Mongo `getWaitForReplicaSetContainer`
- **fix:** improve replica set setup
- **chore:** retryable e2e tests

feat: improvements for Memcached, Mongo, Postgres, and Redis

---

lib/mongo/mongo.ts

During `rs.initiate` MongoDB will try to resolve each member's IP by calling `getaddrinfo` - despite the fact that it connects to the node, resolving address might still fail, e.g.:
```
Waiting for mongo-sts-0.mongo.tarl-replset.svc.cluster.local
{ "ok" : 1 }
Initiating replica set tarl-rs0...
2024-08-19T11:35:55.446+0000 I NETWORK  [thread1] getaddrinfo("mongo-sts-0.mongo.tarl-replset.svc.cluster.local") failed: Name or service not known
2024-08-19T11:35:55.446+0000 E QUERY    [thread1] Error: couldn't initialize connection to host mongo-sts-0.mongo.tarl-replset.svc.cluster.local, address is invalid :
```
The only way around it is to retry the job.

feat: set replica set setup Job backoffLimit

---

e2e/rails-app.e2e.ts
examples/advanced-web-service/__snapshots__/chart.test.ts.snap
examples/advanced-web-service/chart.ts
examples/simple-web-service/__snapshots__/main.test.ts.snap
examples/simple-web-service/main.ts
lib/web-service/web-service.ts
test/web-service/web-service.test.ts

https://techfromsage.atlassian.net/browse/PLT-1083
Problem: While upgrading EKS to Kubernetes 1.30 and 1.31 we ran into issues with Node Group upgrades as they couldn’t evict some Pods. We found the reason to be PodDisruptionBudget violations where PDB is configured with minAvailable: 1 while there is only 1 replica.
Fix: WebService construct validates that when PodDisruptionBudget is enabled, then Deployment’s min replicas is greater (but not equal) than PDB’s minAvailable.

feat: improve pod disruption budget validation

---

e2e/rails-app.e2e.bats

https://techfromsage.atlassian.net/browse/PLT-1083
Problem: PR https://github.com/techfromsage/talis-cdk8s-constructs/pull/98 is merged. After merging we noticed that we are unable to get a green build against main branch which means that there is no release. Problem caused one e2e test which expectation is invalid. Green build on the branch happened because tests are flaky.
Fix: Update e2e test expectation

feat: e2e test correction after improved pdb validation
