examples/advanced-web-service/__snapshots__/chart.test.ts.snap
examples/advanced-web-service/chart.ts
examples/simple-web-service/__snapshots__/main.test.ts.snap
lib/web-service/web-service-props.ts
lib/web-service/web-service.ts
test/web-service/__snapshots__/web-service.test.ts.snap
test/web-service/web-service.test.ts

- Correct Ingress ports annotation to be valid JSON
- Pass through missing command and args props
- Add missing workingDir prop
- Allow to override selectorLabels
- Include namespace in tests and advanced example

fix: correct WebService props

---

examples/advanced-web-service/__snapshots__/chart.test.ts.snap
examples/background-worker/chart.ts
lib/background-worker/background-worker.ts
lib/common/container-props.ts
lib/web-service/web-service-props.ts
lib/web-service/web-service.ts
test/background-worker/__snapshots__/background-worker.test.ts.snap
test/background-worker/background-worker.test.ts
test/web-service/__snapshots__/web-service.test.ts.snap
test/web-service/web-service.test.ts

- Correct HorizontalPodAutoscaler scaleTargetRef.
- Allow to specify imagePullPolicy.
- Correct the name of the tlsDomain prop.

fix: correct HPA and add imagePullPolicy prop

---

README.md
examples/advanced-web-service/__snapshots__/chart.test.ts.snap
examples/advanced-web-service/chart.ts
examples/simple-web-service/__snapshots__/main.test.ts.snap
examples/simple-web-service/main.ts
lib/web-service/annotation-util.ts
lib/web-service/index.ts
lib/web-service/resque-web.ts
lib/web-service/tls-util.ts
lib/web-service/web-service.ts
test/web-service/__snapshots__/resque-web.test.ts.snap
test/web-service/__snapshots__/web-service.test.ts.snap
test/web-service/annotation-util.test.ts
test/web-service/resque-web.test.ts
test/web-service/web-service.test.ts

- [feat: add Ingress annotation helpers](https://github.com/talis/talis-cdk8s-constructs/commit/feb403dd29ae6aafbc2d5af429b7c80710564fda)
- [fix: only use HTTPS if ACM cert can be obtained](https://github.com/talis/talis-cdk8s-constructs/commit/192976b035c853027b5310048502f703ecd6952a)

feat: add Ingress annotation helpers

---

examples/background-worker/__snapshots__/chart.test.ts.snap
examples/background-worker/chart.ts
lib/background-worker/background-worker-props.ts
test/background-worker/__snapshots__/background-worker.test.ts.snap
test/background-worker/background-worker.test.ts
test/data/config-map.test.ts

Tests I included for `stopSignal` in real app would result in `kill: Illegal option -S` error, fixing them here.

docs: update BackgroundWorker stopSignal examples

---

examples/cron-job/__snapshots__/chart.test.ts.snap
examples/job/__snapshots__/chart.test.ts.snap
lib/cron-job/cron-job.ts
lib/job/job.ts
test/cron-job/__snapshots__/cron-job.test.ts.snap
test/cron-job/cron-job.test.ts
test/job/__snapshots__/job.test.ts.snap
test/job/job.test.ts

Some ContainerProps were not handled in Job and CronJob constructs. This fixes that.

fix: respect all container props in Job constructs

---

lib/web-service/web-service-props.ts
lib/web-service/web-service.ts
package-lock.json
test/web-service/__snapshots__/resque-web.test.ts.snap
test/web-service/__snapshots__/web-service.test.ts.snap
test/web-service/resque-web.test.ts
test/web-service/web-service.test.ts

- talis/platform#5483
Allow external hostname to optionally be set for web service.

feat: plat-5483 external hostname

---

README.md
lib/common/env-util.ts
lib/talis-chart/talis-chart.ts
test/common/__snapshots__/env-util.test.ts.snap
test/common/env-util.test.ts
test/talis-chart/talis-chart.test.ts

* https://github.com/talis/platform/issues/5464

feat: add ttl prop to TalisChart

---

lib/common/name-util.ts
lib/talis-chart/talis-chart.ts
lib/talis-chart/talis-deployment-environment.ts
test/common/name-util.test.ts
test/talis-chart/talis-chart.test.ts
test/web-service/annotation-util.test.ts

* https://github.com/talis/elevate-app/issues/5671

feat: add PREVIEW to TalisDeploymentEnvironment enum

---

.npmrc
e2e/full-stack.bats
examples/cron-job/__snapshots__/chart.test.ts.snap
examples/job/__snapshots__/chart.test.ts.snap
lib/cron-job/cron-job.ts
lib/job/job.ts
package-lock.json
package.json
test/cron-job/__snapshots__/cron-job.test.ts.snap
test/cron-job/cron-job.test.ts
test/job/__snapshots__/job.test.ts.snap
test/job/job.test.ts

- https://github.com/talis/platform/issues/5615
- feat: include chart and selector labels on Job Pods
- chore: update dependencies
- chore: set engine-strict=true via .npmrc

feat: include chart and selector labels on Job Pods

---

lib/web-service/web-service-props.ts
lib/web-service/web-service.ts
package-lock.json
package.json
test/web-service/web-service.test.ts

* Expose WebService's KubeService via public prop to allow referencing its DNS name.
* Allow to skip Ingress for services that don't need a load balancer.

feat: add WebService options

---

README.md
e2e/redmine-postgres.e2e.bats
e2e/redmine-postgres.e2e.ts
examples/postgres/README.md
examples/postgres/__snapshots__/chart.test.ts.snap
examples/postgres/cdk8s.yaml
examples/postgres/chart.test.ts
examples/postgres/chart.ts
examples/postgres/main.ts
lib/background-worker/background-worker.ts
lib/common/container-props.ts
lib/cron-job/cron-job-props.ts
lib/index.ts
lib/job/job-props.ts
lib/postgres/index.ts
lib/postgres/postgres-props.ts
lib/postgres/postgres.ts
lib/web-service/web-service-props.ts
lib/web-service/web-service.ts
package.json
test/background-worker/__snapshots__/background-worker.test.ts.snap
test/background-worker/background-worker.test.ts
test/postgres/__snapshots__/postgres.test.ts.snap
test/postgres/postgres.test.ts
test/web-service/__snapshots__/web-service.test.ts.snap
test/web-service/web-service.test.ts

* talis/platform#5692
* Add simple Postgres for standalone on-demand environments

feat: add Postgres construct

---

lib/background-worker/background-worker.ts
lib/cron-job/cron-job-props.ts
lib/cron-job/cron-job.ts
lib/job/job.ts
lib/memcached/memcached.ts
lib/mongo/mongo.ts
lib/postgres/postgres.ts
lib/redis/redis.ts
test/background-worker/background-worker.test.ts
test/cron-job/__snapshots__/cron-job.test.ts.snap
test/cron-job/cron-job.test.ts
test/job/job.test.ts
test/memcached/memcached.test.ts
test/mongo/mongo.test.ts
test/postgres/postgres.test.ts
test/redis/redis.test.ts
test/web-service/web-service.test.ts

- feat: allow to suspend CronJob
- fix: correct precedence order of selector and chart labels

feat: allow CronJob suspend

---

.circleci/config.yml
package-lock.json
package.json

* https://github.com/talis/platform/issues/5696
This P/R adds commit linting to the build. This verifies that all commits on a branch adhere to conventional commits.

ci: add commitlint

---

package.json

:man_facepalming: 
```
Error: ENOENT: no such file or directory, open 'infra/kubernetes/node_modules/talis-cdk8s-constructs/lib/web-service/nginx/default.conf'
```

fix: add missing nginx configs

---

lib/mongo/mongo-props.ts
lib/mongo/mongo.ts
test/mongo/mongo.test.ts

* Allow settings custom arguments for Mongo container

feat: allow custom args for Mongo

---

.circleci/config.yml
e2e/full-stack.bats
e2e/rails-app.e2e.bats
e2e/web-service-canary.bats
lib/background-worker/background-worker-props.ts
package-lock.json
package.json
test/background-worker/__snapshots__/background-worker.test.ts.snap
test/background-worker/background-worker.test.ts

- fix: allow only valid restartPolicy for BackgroundWorker
- chore: update dependencies
- test: only apply from YAML files
- chore: use e2e command in CircleCI

fix: allow only valid `restartPolicy`

---

.circleci/config.yml

* References talis/platform#5988

test: update kubectl

---

lib/common/index.ts
lib/common/value-util.ts
lib/web-service/web-service-props.ts
lib/web-service/web-service.ts
package-lock.json
package.json
test/common/value-util.test.ts
test/web-service/web-service.test.ts

- feat: expose Ingress object from WebService
- docs: add comment for additionalExternalHostnames
- feat: allow multiple TLS domains in WebService
- chore: update dependencies

feat: allow multiple TLS domains in WebService

---

.circleci/config.yml
examples/advanced-web-service/__snapshots__/chart.test.ts.snap
lib/web-service/nginx/samesite.conf
package.json
test/web-service/__snapshots__/nginx-util.test.ts.snap

- plt-302
Update the samesite cookies config for the nginx util from `None` to `Lax`

feat: change to samesite cookies lax in nginx util

---

lib/talis-chart/talis-deployment-environment.ts

Add support for `beta` environments.

feat: add beta deployment environment

---

.circleci/config.yml
cdk8s.yaml
imports/k8s.ts

https://techfromsage.atlassian.net/browse/PLT-718
Update kubectl version to 1.30.3

chore: update kubectl version

---

.circleci/config.yml
cdk8s.yaml
imports/k8s.ts

Reverts talis/talis-cdk8s-constructs#84

chore: revert "chore: update kubectl version"

---

.circleci/config.yml
cdk8s.yaml
imports/k8s.ts

Reverts talis/talis-cdk8s-constructs#85

feat: update kubectl version

---

examples/mongo/__snapshots__/chart.test.ts.snap
examples/mongo/chart.ts
lib/mongo/init/setup-replset.sh
lib/mongo/mongo-props.ts
lib/mongo/mongo.ts
test/mongo/__snapshots__/mongo.test.ts.snap
test/mongo/mongo.test.ts

* Related to [PLT-826](https://techfromsage.atlassian.net/browse/PLT-826)
[PLT-826]: https://techfromsage.atlassian.net/browse/PLT-826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add support for MongoDB replica sets

---

.circleci/config.yml

https://techfromsage.atlassian.net/browse/PLT-1274
Update kubectl version to v1.32.1

feat: update kubectl
